### ISSUE TITLE
Timestamp tests fails

### ISSUE THREAD

**Issue by knoblochtobias** [AckerApple/pdfbox-cli-wrap#4]
I installed the project on my Linux Mint machine.
I'm using Oracle Java 8 (161).
I added BouncyCastle into Java Security Extensions.
I installed Java Cryptography.

But the timestamp tests fails: 
```
15 passing (26s)
  2 failing

  1) pdfboxCliWrap functionality timestamp signatures #sign:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at pdfboxCliWrap.sign.then (test/cases/test.js:103:18)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  2) pdfboxCliWrap functionality timestamp signatures #sign(tsa):

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at pdfboxCliWrap.sign.then (test/cases/test.js:118:18)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

Any ideas?

**Comment by AckerApple** [comment]
I am experiencing the same thing as I am building the Appveyor and Travis tests. Being that its a timestamp errror and its been some time since I've updated the tests... I assume its some time related issue.

Looking into it now

**Comment by AckerApple** [comment]
The fake certificate I am using has expired and the error is NOT being caught.

Working on it now

**Comment by AckerApple** [comment]
Updated testing  process to accommodate that testing certificate may expire.

I still eventually need to update the fake signing certificate but it took too long to update the tests so I will address at a later date.
