### ISSUE TITLE
Use eslint

### ISSUE THREAD

**Issue by knoblochtobias** [AckerApple/pdfbox-cli-wrap#5]
You could use eslint to get clean js code.

Good point to start:
[Eslint: getting started ](https://eslint.org/docs/user-guide/getting-started)
[useful standard rules from airnbnb](https://www.npmjs.com/package/eslint-config-airbnb-base)
[integrate it in vs code editor](https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6)

**Comment by AckerApple** [comment]
clean code? Oh you trying to start sumfin?

Yo just messin' with you. Me and my brother have gone back and forth over the lint.

I'll write the code in Typescript and cast it to JS code long before I will lint. Lint'ing is still too restrictive to me and we could go circles on and on...

Thank you kindly. Not likely to happen.

What are your extra thoughts I might want to hear? I've been slapping down the lint for some years now

**Comment by knoblochtobias** [comment]
Just an idea ;)

I like it if my code is clean, so i'm using a linter in most of my projects...

**Comment by AckerApple** [comment]
I've had great success moving to TypeScript and then running one of them NodeTs interpreters. It gives me far more descriptive code with more scripting like declarations that ultimately resolves in cleaner more condensed code. I like that route over an enforcer but its kinda comparing apples to oranges so I know my points are hella debatable and in some cases invalid.........

Closing point as to why I may still do nothing and not make a change.... I feel the less requirements to build a project, the more anybodies are attracted to make a pull request. I've not worked on packages based on complicated restrictive build processes.

With unit tests, I'm ok with "dirty" code. I love my code style, so suck it!

Nah, you be good. Love a good chat. I'm cool to leave this issue open for a while. Bout time this package got some attention, it's good shit I use in production.

**Comment by AckerApple** [comment]
This package's JS files are now built from TS files.

Typings have not yet been utilized to there fullest but Typescript code checking already found a bunch of items I needed to correct.

The future of this task would be to increase the amount of typings so that this package is NOT too loose.
